server:
  port: 8000
mongodb:
  ip: 127.0.0.1
  port: 27017
  username: root
  password: "123456"
  database: sft
minio:
  ip: 172.17.0.2
  port: 9000
  bucket: sft
  access_key: minioadmin
  secret_key: minioadmin
  secure: false
