server:
  port: 8000
mongo:
  ip: ${SERVER_IP}
  port: 27017
  username: ${MONGO_USER_NAME}
  password: ${MONGO_USER_PASSWORD}
  database: ${MONGO_DATABASE}
minio:
  ip: ${SERVER_IP}
  port: 9000
  bucket: sft
  access_key: ${MINIO_ACCESS_KEY}
  secret_key: ${MINIO_SECRET_KEY}
  secure: false
  policy: public
